name: Cake-Linter

on: push

jobs:
  super-lint:
    name: List code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/cakemgr
        
      - name: Run Cake-Linter
        uses: github/cakemgr
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
